succeeds {
  function add(x,y) :: int, int -> int {
    return x+y;
  }
}
{
  if (add(10,12) != 22) {
    throw "epic fail";
  }
};

blames "client" {
  function add(x,y) :: int, int -> int {
    return x+y;
  }
}
{
  add("ten","eleven");
};

succeeds {
  var add = function(x,y) :: int, int -> int {
    return x;
  }
  var z = add(undefined, undefined);
}
{
  add(undefined, undefined);
};

succeeds {
  var add = function(x,y) :: int, int -> int {
    return x+y;
  }
  var z = add(undefined, undefined);
}
{
  add(undefined, undefined);
};

blames "chocolate" {
  function foo() :: -> int {
    throw "chocolate violated the contract; haha funny";
  }
}
{
  foo();
};
